SIMPLY list

In [ ]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [ ]:
b = [6,12,17,22]
b

[6, 12, 17, 22]

In [ ]:
a.extend(b)
a

[1, 2, 3, 4, 6, 12, 17, 22]

In [ ]:
a.append(b)
a

[1, 2, 3, 4, [6, 12, 17, 22]]

In [ ]:
a.insert(3,18)

In [ ]:
a

[1, 2, 3, 18, 4, [6, 12, 17, 22]]

In [ ]:
c=(1,2,3,5,4,6)
c

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a.shape

(4,)

In [ ]:
b= np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
b.shape

(2, 2)

In [ ]:
seq=np.arange(2,11)
seq

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=np.array([1,2,3,4],dtype=np.float64)#int32
a.dtype

dtype('float64')

In [ ]:
type(a)

numpy.ndarray

In [ ]:
z=np.zeros(3)
z

array([0., 0., 0.])

In [ ]:
r=np.random.random(3)
r

array([0.37223055, 0.35838621, 0.30550306])

In [ ]:
o=np.ones(4)

In [ ]:
# 2d
o=np.ones((4,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
r1=np.random.random((3,2,2))
print(r1)
print("-----------")
r2=np.random.random((3,2))
r2

[[[0.98423295 0.72033706]
  [0.94501097 0.14648422]]

 [[0.87653792 0.2890781 ]
  [0.62271529 0.11948351]]

 [[0.67412437 0.45196663]
  [0.50595975 0.00230806]]]
-----------


array([[0.32935692, 0.44666801],
       [0.41474429, 0.37118887],
       [0.75798026, 0.44969253]])

In [ ]:
r3=np.zeros((4,3))
r3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
print(np.full((2,3),4))
np.eye(3)

[[4 4 4]
 [4 4 4]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
f=np.arange(10,50,5)
f

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
g=np.linspace(0,1,num=5)
g

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
data=np.array([1,3,4,5,6,7,8])
print(data[0:])
print(data[4:6])
print(data[0:2])

[1 3 4 5 6 7 8]
[6 7]
[1 3]


In [ ]:
da=np.array([[1,2,3],[4,5,6]])
print(da[0:2,0])

[1 4]


In [ ]:
print(da[0:2,2])

[3 6]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
row1=a[1,:]
print(row1,row1.shape)

row2=a[0:2,3]
print(row2,row2.shape)
#column1
row3=a[:,2]
print(row3,row3.shape)

row4=a[1:2,:]
print(row4,row4.shape)

row5=a[[1],:]
print(row5,row5.shape)
#column2
col2=a[:,1:2]
print(col2,col2.shape)

[5 6 7 8] (4,)
[4 8] (2,)
[ 3  7 11] (3,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
b=np.array([0,2,0,1])
print(a[np.arange(4),b])

[ 1  6  7 11]


In [ ]:
a[np.arange(4),b]+=10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
bool2=(a>4)
bool2

array([[False, False],
       [False, False],
       [ True,  True]])

In [ ]:
a=[0]
a=np.append(a,[1,2,3,4])
print(a)

[0 1 2 3 4]


In [ ]:
a=np.delete(a,[3])
print(a)

[0 1 2 4]


In [ ]:
print(np.where(a<2))
print(np.where(a<a[np.argmax(a)]))

(array([0, 1]),)
(array([0, 1, 2]),)


In [ ]:
a=np.array([1,2,3,4,5,6])
x=np.sum(a)
x

21

In [ ]:
%%time
x=0
for i in a:
  x+=i
  print(x)

1
3
6
10
15
21
CPU times: user 1 ms, sys: 1.9 ms, total: 2.91 ms
Wall time: 3.39 ms


In [ ]:
%%time
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x*y)
print(x.dot(y))#or
print(np.dot(x,y))#or
print(x@y)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
CPU times: user 3.37 ms, sys: 0 ns, total: 3.37 ms
Wall time: 5.39 ms


In [ ]:
x.reshape(1,4)
x

array([[1, 2],
       [3, 4]])

squeeze()- will remove extra braces and space

In [ ]:
w=np.array([[1],[2],[3]])
print(w)
y=w.reshape(-1,)
print(y)#or
print(w.squeeze())

[[1]
 [2]
 [3]]
[1 2 3]
[1 2 3]


In [ ]:
#broadcasting
a=np.array([1,2,3,4])+1
print(a)
b=np.array([[4,5,6],[7,8,9]])+np.array([1,2,3])
print(b)

[2 3 4 5]
[[ 5  7  9]
 [ 8 10 12]]


NameError: ignored